import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Param,
  Body,
} from '@nestjs/common';
import { ProductService } from './product.service';
import { Product } from './product.entity';

@Controller('products')
export class ProductController {
  constructor(private readonly productService: ProductService) {}

  @Get()
  async findAll(): Promise<Product[]> {
    return this.productService.findAll(); // Fetch all products
  }

  @Get(':id')
  async findOne(@Param('id') id: number): Promise<Product> {
    return this.productService.findOne(id); // Fetch product by ID
  }

  @Post()
  async create(@Body() product: Partial<Product>): Promise<Product> {
    return this.productService.create(product); // Create a new product, returning the created product, including the ID
    // Note: The ID is generated by the database, so it won't be in the request body.
    // The created product will be returned with the ID included.
    // The ID will be automatically generated by the database when the product is created.
    // The response will include the ID of the newly created product.
    // The ID will be generated by the database when the product is created.
    // The response will include the ID of the newly created product.
    // The ID will be generated by the database when the product is created.
    // The response will include the ID of the newly created product.
  }

  @Put(':id')
  async update(
    @Param('id') id: number,
    @Body() product: Partial<Product>,
  ): Promise<Product> {
    return this.productService.update(id, product); // Update product by ID
  }

  @Delete(':id')
  async delete(@Param('id') id: number): Promise<void> {
    return this.productService.delete(id); // Delete product by ID
  }
}
